---
abstract: 'Use Imager in Mojolicious'
author:
  - 'Andrey Gatitskiy <gatitskiy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Thumbnail
no_index:
  directory:
    - t
    - inc
requires:
  Imager: '0'
  Mojolicious: '0'
version: '0.01'
